#!/bin/bash

# This will generate files required by ANTLR runtime in order to process an Integer expression source file
# using Python as the language in which we will code our parser
# In short, the useful output of this command are .py files generated by it.
antlr4 -Dlanguage=Python3 grammar/Expr.g4 -visitor -Xexact-output-dir -o ./python_files/
